version: '3.8'

services:
  app:
    image: contact-manager
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contactdbMig
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1389
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"
  db:
    image: postgres
#    build:
#      context: ./DockerDB
#      dockerfile: Dockerfile
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=andrija
      - POSTGRES_PASSWORD=1389
      - POSTGRES_DB=contactdbMig
    ports:
      - "5432:5432"
    volumes:
      - ./log-directory:/var/lib/postgresql/data